# .travis.yml
language: go
go:
  - "1.10"

install:
    - go get -v github.com/vjeantet/bitfan/commons/xprocessor
  
# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
